<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Preparation – Computer Systems Design Analytics Career Pathways</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-b6702f791c3d41e5b398c65af8f053e9.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Computer Systems Design Analytics Career Pathways</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./introduction.html"> 
<span class="menu-text">Project Foundation</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-market-analysis" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Market Analysis</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-market-analysis">    
        <li>
    <a class="dropdown-item" href="./data_preparation.html">
 <span class="dropdown-text">Data Preparation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./market_baseline.html">
 <span class="dropdown-text">Market Baseline</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-career-evaluation" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Career Evaluation</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-career-evaluation">    
        <li>
    <a class="dropdown-item" href="./skill_gap_analysis.html">
 <span class="dropdown-text">Skill-Gap Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./career_evaluation.html">
 <span class="dropdown-text">Career Scorecard</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./final_recommendations.html"> 
<span class="menu-text">Recommendations</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">Team</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/JennaDer/METAD688_Group2"> <i class="bi bi-github" role="img" aria-label="GitHub Repository">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#project-scope" id="toc-project-scope" class="nav-link active" data-scroll-target="#project-scope">Project Scope</a>
  <ul class="collapse">
  <li><a href="#note-on-the-industry-change" id="toc-note-on-the-industry-change" class="nav-link" data-scroll-target="#note-on-the-industry-change">Note on the industry change</a></li>
  </ul></li>
  <li><a href="#data-source-and-connection" id="toc-data-source-and-connection" class="nav-link" data-scroll-target="#data-source-and-connection">Data Source and Connection</a></li>
  <li><a href="#industry-filter" id="toc-industry-filter" class="nav-link" data-scroll-target="#industry-filter">Industry Filter</a></li>
  <li><a href="#career-pathway-filter" id="toc-career-pathway-filter" class="nav-link" data-scroll-target="#career-pathway-filter">Career-Pathway Filter</a></li>
  <li><a href="#record-counts" id="toc-record-counts" class="nav-link" data-scroll-target="#record-counts">Record Counts</a></li>
  <li><a href="#date-window" id="toc-date-window" class="nav-link" data-scroll-target="#date-window">Date Window</a></li>
  <li><a href="#cleaning-decisions" id="toc-cleaning-decisions" class="nav-link" data-scroll-target="#cleaning-decisions">Cleaning Decisions</a>
  <ul class="collapse">
  <li><a href="#duplicate-records" id="toc-duplicate-records" class="nav-link" data-scroll-target="#duplicate-records">Duplicate Records</a></li>
  <li><a href="#salary" id="toc-salary" class="nav-link" data-scroll-target="#salary">Salary</a></li>
  <li><a href="#experience-requirements" id="toc-experience-requirements" class="nav-link" data-scroll-target="#experience-requirements">Experience Requirements</a></li>
  <li><a href="#education-requirements" id="toc-education-requirements" class="nav-link" data-scroll-target="#education-requirements">Education Requirements</a></li>
  <li><a href="#skill-fields" id="toc-skill-fields" class="nav-link" data-scroll-target="#skill-fields">Skill Fields</a></li>
  <li><a href="#remote-and-onsite-indicators" id="toc-remote-and-onsite-indicators" class="nav-link" data-scroll-target="#remote-and-onsite-indicators">Remote and Onsite Indicators</a></li>
  <li><a href="#location-fields" id="toc-location-fields" class="nav-link" data-scroll-target="#location-fields">Location Fields</a></li>
  <li><a href="#industry-and-occupation-fields" id="toc-industry-and-occupation-fields" class="nav-link" data-scroll-target="#industry-and-occupation-fields">Industry and Occupation Fields</a></li>
  <li><a href="#inconsistent-labels" id="toc-inconsistent-labels" class="nav-link" data-scroll-target="#inconsistent-labels">Inconsistent Labels</a></li>
  </ul></li>
  <li><a href="#missing-value-summary" id="toc-missing-value-summary" class="nav-link" data-scroll-target="#missing-value-summary">Missing-Value Summary</a></li>
  <li><a href="#analytical-limitations" id="toc-analytical-limitations" class="nav-link" data-scroll-target="#analytical-limitations">Analytical Limitations</a></li>
  <li><a href="#output" id="toc-output" class="nav-link" data-scroll-target="#output">Output</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Data Preparation</h1>
<p class="subtitle lead">Module 2 — Filtering and Cleaning the Career Market Panel</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="project-scope" class="level2">
<h2 class="anchored" data-anchor-id="project-scope">Project Scope</h2>
<p>This page documents how the raw CareerCompass extract was reduced to the analytical panel used throughout the rest of the site. The panel covers one industry and one career pathway, as the project scope requires.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Element</th>
<th>Selection</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Industry</td>
<td>Computer Systems Design and Related Services</td>
</tr>
<tr class="even">
<td>NAICS 2022 code</td>
<td>5415</td>
</tr>
<tr class="odd">
<td>Career pathway</td>
<td>Analytics roles: data analyst, data scientist, data engineer, business intelligence, business analyst</td>
</tr>
<tr class="even">
<td>Date window</td>
<td>2026-03-25 to 2026-06-29</td>
</tr>
<tr class="odd">
<td>Final panel size</td>
<td>287 postings</td>
</tr>
</tbody>
</table>
<section id="note-on-the-industry-change" class="level3">
<h3 class="anchored" data-anchor-id="note-on-the-industry-change">Note on the industry change</h3>
<p>This project was originally scoped to Pharmaceutical and Medicine Manufacturing (NAICS 3254). We abandoned that scope in Module 2 after a volume check returned only 39 postings across the entire extract, falling to between 2 and 5 once analytics roles were isolated. A sample that small cannot support salary, geographic, or skill analysis.</p>
<p>We checked every manufacturing code before moving on. The sector as a whole held 313 analytics postings, and no single four-digit manufacturing code exceeded 57. We selected NAICS 5415 because it is a standard four-digit code, it appears in the assignment’s own list of relevant industries, and it carries enough volume to support the required analysis.</p>
</section>
</section>
<section id="data-source-and-connection" class="level2">
<h2 class="anchored" data-anchor-id="data-source-and-connection">Data Source and Connection</h2>
<p>The source is the MET CareerCompass 2026 job-postings extract, supplied as 17 Parquet partitions holding 165,386 postings and 115 variables.</p>
<p>The raw files are not committed to this repository. Each team member downloads them from the course-provided folder and points a local path at the download location, as described in the README. The processed panel produced by this page is committed, so the rest of the site renders without access to the raw extract.</p>
<p>Filtering and cleaning run in PySpark through <code>scripts/build_panel.py</code>, which imports two helper modules, <code>scripts/clean_location.py</code> and <code>scripts/clean_salary.py</code>. The script writes one output file, <code>data/processed/career_market_panel.csv</code>.</p>
</section>
<section id="industry-filter" class="level2">
<h2 class="anchored" data-anchor-id="industry-filter">Industry Filter</h2>
<p>We filtered on <code>NAICS_2022_4</code>, the four-digit 2022 NAICS code attached to each posting. The extract also carries two-, three-, five-, and six-digit variants. We used the four-digit field because the assignment specifies four- or six-digit codes, and because <code>NAICS_2022_4_NAME</code> is blank throughout the extract while <code>NAICS_2022_6_NAME</code> is populated and supplies the industry label.</p>
</section>
<section id="career-pathway-filter" class="level2">
<h2 class="anchored" data-anchor-id="career-pathway-filter">Career-Pathway Filter</h2>
<p>Filtering on the word “analyst” alone was not workable. Within NAICS 5415 it returned 621 postings, but the results included security analysts, QA analysts, trade compliance analysts, and IT support analysts. “Analyst” functions as a generic corporate suffix, and including those roles would distort both the skill analysis and the salary distribution.</p>
<p>We therefore defined the role family positively, matching titles that name an analytics role directly rather than excluding unwanted ones after the fact.</p>
<p><strong>Included patterns:</strong> <code>data analyst</code>, <code>data scien</code>, <code>business intelligence</code>, <code>bi analyst</code>, <code>data engineer</code>, <code>analytics engineer</code>, <code>business analyst</code>, <code>reporting analyst</code></p>
<p><strong>Excluded patterns:</strong> <code>security</code>, <code>qa</code>, <code>quality assurance</code>, <code>support</code>, <code>trade</code>, <code>exploitation</code>, <code>acceptance testing</code>, <code>network</code></p>
<p>The exclusion rule removed only two further postings, which confirms the positive definition was doing the work. We kept it in place as a documented check.</p>
</section>
<section id="record-counts" class="level2">
<h2 class="anchored" data-anchor-id="record-counts">Record Counts</h2>
<div class="cell" data-execution_count="2">
<div id="tbl-funnel" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-funnel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1
</figcaption>
<div aria-describedby="tbl-funnel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Step</th>
<th data-quarto-table-cell-role="th">Postings</th>
<th data-quarto-table-cell-role="th">Retained</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Raw extract</td>
<td>165386</td>
<td>100.0%</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>After NAICS 5415 filter</td>
<td>8855</td>
<td>5.35%</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>After role-family inclusion</td>
<td>289</td>
<td>0.17%</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>After role-family exclusion</td>
<td>287</td>
<td>0.17%</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>After valid posted date</td>
<td>287</td>
<td>0.17%</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="date-window" class="level2">
<h2 class="anchored" data-anchor-id="date-window">Date Window</h2>
<p>Every posting in the panel carries a valid <code>POSTED</code> date, so no records were lost at this stage.</p>
<div id="date-window" class="cell" data-execution_count="3">
<div class="cell-output cell-output-stdout">
<pre><code>Earliest posting: 2026-03-25
Latest posting:   2026-06-29
Span:             96 days</code></pre>
</div>
</div>
<p>The extract covers a single quarter. Rather than impose a narrower window on an already narrow range, we kept the full span and recorded it. Any seasonal pattern in analytics hiring cannot be observed in three months of data, and we note this as a limitation rather than attempting to correct for it.</p>
</section>
<section id="cleaning-decisions" class="level2">
<h2 class="anchored" data-anchor-id="cleaning-decisions">Cleaning Decisions</h2>
<section id="duplicate-records" class="level3">
<h3 class="anchored" data-anchor-id="duplicate-records">Duplicate Records</h3>
<p>All 287 postings carry a unique <code>ID</code>, so the panel contains no exact duplicates. The <code>DUPLICATES</code> field supplied with the extract is blank on every row and provided no help.</p>
<p>Grouping by title, employer, and posted date does surface repeats. Inspection showed these are multi-location postings rather than duplicates: Esri, for example, advertised the same Enterprise Data Engineer role separately for California, Missouri, and Virginia, each with its own record ID. We kept these, since a single opening advertised in three states is three opportunities from a job seeker’s perspective. The effect is that geographic counts are slightly inflated relative to the number of distinct openings, and we note that where geography is discussed.</p>
</section>
<section id="salary" class="level3">
<h3 class="anchored" data-anchor-id="salary">Salary</h3>
<p>Salary required the most cleaning. <code>SALARY_FROM</code> and <code>SALARY_TO</code> are stored as strings and are blank on most rows.</p>
<p>Three rules were applied:</p>
<ul>
<li>Rows carrying <code>0.00</code> were treated as missing rather than as a salary of zero. Four postings had this pattern, all of them cases where the source held a structured <code>MonetaryAmount</code> object the provider could not flatten.</li>
<li>One posting listed an annual salary of $401, which is implausible. We set a floor of $20,000 and excluded it.</li>
<li>Four postings quoted hourly rates. These were converted to annual equivalents at 2,080 hours so that all salary figures sit on one scale.</li>
</ul>
<div class="cell" data-execution_count="4">
<div id="tbl-salary" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="4">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-salary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2
</figcaption>
<div aria-describedby="tbl-salary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Measure</th>
<th data-quarto-table-cell-role="th">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Postings with usable salary</td>
<td>112</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Share of panel</td>
<td>39%</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Minimum</td>
<td>$66,560</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Median</td>
<td>$150,708</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>Mean</td>
<td>$156,043</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>Maximum</td>
<td>$318,250</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>We report the midpoint of the advertised range. Where only a lower bound exists, the lower bound is used. Coverage is 39 percent of the panel, which is normal for job-posting data, and salary findings should be read as describing the postings that disclose pay rather than the market as a whole.</p>
</section>
<section id="experience-requirements" class="level3">
<h3 class="anchored" data-anchor-id="experience-requirements">Experience Requirements</h3>
<p><code>MIN_YEARS_EXPERIENCE</code> and <code>MAX_YEARS_EXPERIENCE</code> are blank on all 165,386 rows of the extract, not only within our filtered panel. No experience analysis is possible from this field.</p>
<p>We substitute the education distribution where an experience requirement would otherwise be reported, and flag the gap in the limitations section.</p>
</section>
<section id="education-requirements" class="level3">
<h3 class="anchored" data-anchor-id="education-requirements">Education Requirements</h3>
<p>Six education fields are populated on every posting. We examined both the minimum and maximum fields and use the maximum.</p>
<p><code>MIN_EDULEVELS_NAME</code> records “Associate’s degree” on 235 of 287 postings, which reads as a modeled floor rather than a stated employer requirement. Charting it would produce a single dominant category carrying no information.</p>
<div class="cell" data-execution_count="5">
<div id="tbl-education" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="5">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-education-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3
</figcaption>
<div aria-describedby="tbl-education-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Highest education level listed</th>
<th data-quarto-table-cell-role="th">Postings</th>
<th data-quarto-table-cell-role="th">Share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Master's degree</td>
<td>101</td>
<td>35.2%</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Bachelor's degree</td>
<td>94</td>
<td>32.8%</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Associate's degree</td>
<td>48</td>
<td>16.7%</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Doctoral or professional degree</td>
<td>44</td>
<td>15.3%</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="skill-fields" class="level3">
<h3 class="anchored" data-anchor-id="skill-fields">Skill Fields</h3>
<p>The extract carries four skill families. Coverage within the panel is uneven:</p>
<ul>
<li><code>SKILLS_NAME</code>: 278 of 287 postings</li>
<li><code>SPECIALIZED_SKILLS_NAME</code>: 277 of 287</li>
<li><code>COMMON_SKILLS_NAME</code>: 82 of 287</li>
<li><code>SOFTWARE_SKILLS_NAME</code>: present on 278 rows but containing an empty array in every case</li>
</ul>
<p>A more serious problem affects all of them. Across the full extract of 165,386 postings there are 2,025 distinct values in <code>SKILLS_NAME</code>, and <strong>not one begins with a letter between D and Z</strong>. The same holds for <code>SPECIALIZED_SKILLS_NAME</code>, which carries 1,834 distinct values under the same constraint.</p>
<p>The practical consequence is that no posting in the dataset lists Python, SQL, R, Tableau, Power BI, Spark, or any other tool whose name falls in that range. The skill lists appear to have been alphabetically truncated before delivery.</p>
<p>We report skill findings from what is present and flag the truncation prominently wherever skills are discussed. This limitation affects the skill-gap analysis in Step 3 directly, and we have raised it with the instructor.</p>
</section>
<section id="remote-and-onsite-indicators" class="level3">
<h3 class="anchored" data-anchor-id="remote-and-onsite-indicators">Remote and Onsite Indicators</h3>
<p><code>REMOTE_TYPE_NAME</code> classifies 142 of 287 postings. The remaining 145 are recorded as “Unknown”.</p>
<p>We verified that Unknown means unclassified rather than misclassified: every posting whose <code>LOCATION</code> text mentions remote work is already flagged Remote or Hybrid, so no records needed recovery. Unknown is reported as its own category and is not treated as onsite.</p>
<div class="cell" data-execution_count="6">
<div id="tbl-remote" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="6">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-remote-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4
</figcaption>
<div aria-describedby="tbl-remote-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Work arrangement</th>
<th data-quarto-table-cell-role="th">Postings</th>
<th data-quarto-table-cell-role="th">Share of panel</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Unknown</td>
<td>145</td>
<td>50.5%</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Remote</td>
<td>65</td>
<td>22.6%</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Hybrid</td>
<td>54</td>
<td>18.8%</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>On-site</td>
<td>23</td>
<td>8.0%</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="location-fields" class="level3">
<h3 class="anchored" data-anchor-id="location-fields">Location Fields</h3>
<p>The location fields in the extract are unreliable. <code>STATE_NAME</code> holds a valid state name on only about 65 of 287 postings; the rest contain “United States”, “Remote”, city fragments such as “Francisco” and “Austin”, or blanks. The structured alternatives are sparser still, with <code>STATE</code> populated on 92 postings, <code>COUNTY_NAME</code> on 39, and <code>MSA_NAME</code> on 16.</p>
<p><code>LOCATION</code> is the only location field populated on every row, but it is free text with no consistent structure.</p>
<p>We built a derived <code>state</code> column using a four-stage rule, implemented in <code>scripts/clean_location.py</code>:</p>
<ol type="1">
<li>Match a full state name inside <code>LOCATION</code></li>
<li>Otherwise match a two-letter state code between delimiters</li>
<li>Otherwise fall back to the <code>STATE</code> column</li>
<li>Otherwise map a small set of bare city names to their states</li>
</ol>
<p>Two-letter codes recovered at any stage are normalized to full state names so that “CA” and “California” do not appear as separate categories.</p>
<div id="location-recovery" class="cell" data-execution_count="7">
<div class="cell-output cell-output-stdout">
<pre><code>Postings with a recovered state: 205 of 287 (71%)
Distinct states represented:     29</code></pre>
</div>
</div>
<p>The 82 remaining postings are genuinely locationless: their <code>LOCATION</code> reads “United States”, “Remote”, “US”, or “USA”. These are reported as Unspecified rather than dropped, since a nationwide or remote posting is a real category rather than missing data.</p>
</section>
<section id="industry-and-occupation-fields" class="level3">
<h3 class="anchored" data-anchor-id="industry-and-occupation-fields">Industry and Occupation Fields</h3>
<p><code>NAICS_2022_4_NAME</code> is blank throughout the extract, so the industry label is taken from <code>NAICS_2022_6_NAME</code>, which reads “Computer Systems Design and Related Services” on all 287 rows.</p>
<p>For occupation we use <code>ONET_NAME</code>, a controlled vocabulary, in preference to raw job titles. Titles are free text, so “Senior Data Analyst” and “Data Analyst - Senior” would otherwise count as separate roles.</p>
<p>ONET misclassified eight postings, placing them under “Models”, “Actors”, or “Information Security Analysts”. Inspection confirmed all eight are genuine analytics roles, including Advanced Data Analyst, Business Intelligence Developer, and People Data Analyst. We kept them and grouped them as “Other”, since our title filter rather than ONET defines membership in the role family.</p>
<div class="cell" data-execution_count="8">
<div id="tbl-occupation" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="8">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-occupation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5
</figcaption>
<div aria-describedby="tbl-occupation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="8">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Occupation group</th>
<th data-quarto-table-cell-role="th">Postings</th>
<th data-quarto-table-cell-role="th">Share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Data Scientists</td>
<td>135</td>
<td>47.0%</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Database Architects</td>
<td>98</td>
<td>34.1%</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Management Analysts</td>
<td>33</td>
<td>11.5%</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Other</td>
<td>16</td>
<td>5.6%</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>Business Intelligence Analysts</td>
<td>5</td>
<td>1.7%</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="inconsistent-labels" class="level3">
<h3 class="anchored" data-anchor-id="inconsistent-labels">Inconsistent Labels</h3>
<p>Employer names are not standardized. Three patterns appear:</p>
<ul>
<li>The same company under different spellings, such as “Turnitin” and “Turnitinllc”, and “Anduril Industries” and “Andurilindustries”</li>
<li>Applicant tracking system URLs recorded as the employer, such as “Jobs.baesystems.com” and “Careers.pnc.com”</li>
<li>Job titles differing only in spacing, such as “Technical Consultant- Enterprise Data Engineer” and “Technical Consultant - Enterprise Data Engineer”</li>
</ul>
<p>We left employer names as supplied rather than merging them, since any merge rule risks combining genuinely distinct entities. Employer counts should therefore be read as approximate, and the pattern is noted wherever employers are discussed.</p>
</section>
</section>
<section id="missing-value-summary" class="level2">
<h2 class="anchored" data-anchor-id="missing-value-summary">Missing-Value Summary</h2>
<div class="cell" data-execution_count="9">
<div id="tbl-missing" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="9">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-missing-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6
</figcaption>
<div aria-describedby="tbl-missing-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="9">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Field</th>
<th data-quarto-table-cell-role="th">Populated</th>
<th data-quarto-table-cell-role="th">Missing</th>
<th data-quarto-table-cell-role="th">Coverage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Job title</td>
<td>287</td>
<td>0</td>
<td>100%</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Employer</td>
<td>287</td>
<td>0</td>
<td>100%</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Occupation group</td>
<td>287</td>
<td>0</td>
<td>100%</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Posted date</td>
<td>287</td>
<td>0</td>
<td>100%</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>State (derived)</td>
<td>205</td>
<td>82</td>
<td>71%</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>Work arrangement</td>
<td>142</td>
<td>145</td>
<td>49%</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>Education (max)</td>
<td>287</td>
<td>0</td>
<td>100%</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>Salary midpoint</td>
<td>112</td>
<td>175</td>
<td>39%</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>Skills</td>
<td>278</td>
<td>9</td>
<td>97%</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>Coverage varies widely. Title, employer, occupation, date, and education are complete. Salary, location, and work arrangement are partial, and each is reported against its own denominator rather than against the full panel. Experience is absent entirely.</p>
</section>
<section id="analytical-limitations" class="level2">
<h2 class="anchored" data-anchor-id="analytical-limitations">Analytical Limitations</h2>
<p>Five limitations carry into the rest of the project.</p>
<p><strong>Skill lists are alphabetically truncated.</strong> No skill beginning with a letter from D to Z appears anywhere in the source extract. Python, SQL, R, Tableau, and similar tools cannot be observed. This constrains the skill-gap analysis in Step 3 more than any other issue on this page.</p>
<p><strong>Experience requirements are absent.</strong> Both experience fields are blank across all 165,386 postings, so the analysis substitutes education where experience would otherwise be reported.</p>
<p><strong>Salary reflects disclosing employers only.</strong> Pay appears on 39 percent of postings. Employers that disclose salary may differ systematically from those that do not, so salary figures describe the disclosing subset rather than the market.</p>
<p><strong>The window is one quarter.</strong> The extract spans 2026-03-25 to 2026-06-29. Seasonal hiring patterns cannot be observed, and any trend over time within the panel should be treated as noise rather than signal.</p>
<p><strong>The panel is a sample, not a census.</strong> 287 postings in one industry over one quarter is enough to describe patterns, not enough to estimate market size. Findings are stated as what these postings show rather than as claims about analytics hiring nationally.</p>
</section>
<section id="output" class="level2">
<h2 class="anchored" data-anchor-id="output">Output</h2>
<p>The cleaned panel is written to <code>data/processed/career_market_panel.csv</code> and is committed to the repository so the remaining pages render without access to the raw extract.</p>
<div class="cell" data-execution_count="10">
<div id="tbl-schema" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="10">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-schema-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7
</figcaption>
<div aria-describedby="tbl-schema-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="10">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Column</th>
<th data-quarto-table-cell-role="th">Type</th>
<th data-quarto-table-cell-role="th">Non-null</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>ID</td>
<td>int64</td>
<td>287</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>TITLE_CLEAN</td>
<td>object</td>
<td>287</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>COMPANY_NAME</td>
<td>object</td>
<td>287</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>COMPANY_IS_STAFFING</td>
<td>bool</td>
<td>287</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>occupation_group</td>
<td>object</td>
<td>287</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>posted_date</td>
<td>object</td>
<td>287</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>state</td>
<td>object</td>
<td>287</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>LOCATION</td>
<td>object</td>
<td>287</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>REMOTE_TYPE_NAME</td>
<td>object</td>
<td>287</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>MAX_EDULEVELS_NAME</td>
<td>object</td>
<td>287</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>MIN_EDULEVELS_NAME</td>
<td>object</td>
<td>287</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>salary_from_annual</td>
<td>float64</td>
<td>112</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>salary_to_annual</td>
<td>float64</td>
<td>112</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>salary_midpoint</td>
<td>float64</td>
<td>112</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>ORIGINAL_PAY_PERIOD</td>
<td>object</td>
<td>122</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">15</th>
<td>SKILLS_NAME</td>
<td>object</td>
<td>278</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">16</th>
<td>SPECIALIZED_SKILLS_NAME</td>
<td>object</td>
<td>278</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">17</th>
<td>NAICS_2022_4</td>
<td>int64</td>
<td>287</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">18</th>
<td>NAICS_2022_6_NAME</td>
<td>object</td>
<td>287</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>To rebuild the panel from source, place the 17 Parquet files in <code>data/MET_CareerCompass_2026/</code> and run:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> scripts/build_panel.py</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/JennaDer\.github\.io\/METAD688_Group2\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>MET AD 688 | Group 2</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>NAICS 5415 — Computer Systems Design and Related Services</p>
</div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>